
name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run Tests
        run: yarn test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --no-lockfile
      - name: Run Tests
        run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-classic
        experimental: [false]
        include:
          - try-scenario: ember-beta
            experimental: true
          - try-scenario: ember-canary
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn ember try:one ${{ matrix.try-scenario }}
